DROP TABLE IF EXISTS tags;
--;;
DROP TABLE IF EXISTS tag_relations;
--;;
DROP TABLE IF EXISTS projects;
--;;
DROP TABLE IF EXISTS repos;
--;;
DROP TABLE IF EXISTS repo_default_tag_mapping;
--;;
DROP TABLE IF EXISTS issues;
--;;
DROP TABLE IF EXISTS branches;
--;;
DROP TABLE IF EXISTS named_tags;
--;;
DROP TABLE IF EXISTS g2_repo_label_mapping;
--;;
DROP TABLE IF EXISTS repository_labels;
--;;
DROP TABLE IF EXISTS issues_labels;
--;;
DROP TABLE IF EXISTS users;
--;;
DROP TABLE IF EXISTS zeus_users;
--;;
DROP TABLE IF EXISTS github_user;
--;;
DROP TABLE IF EXISTS repository_providers;
--;;
